//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuPogodi.AppLogic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuPogodi.AppLogic.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remake of the original handheld game Ну, погоди! (You Just Wait!, 1986, SSSR) for Windows Phone..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu, Pogodi!.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nupogodi.suchan.cz/.
        /// </summary>
        public static string AppWeb {
            get {
                return ResourceManager.GetString("AppWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to highscore.
        /// </summary>
        public static string Highscore {
            get {
                return ResourceManager.GetString("Highscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game a.
        /// </summary>
        public static string ModeA {
            get {
                return ResourceManager.GetString("ModeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to game b.
        /// </summary>
        public static string ModeB {
            get {
                return ResourceManager.GetString("ModeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now!.
        /// </summary>
        public static string TrialBuy {
            get {
                return ResourceManager.GetString("TrialBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version ends after collecting {0} points in the game. Do you think you can do more?.
        /// </summary>
        public static string TrialMessage {
            get {
                return ResourceManager.GetString("TrialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string TrialNotNow {
            get {
                return ResourceManager.GetString("TrialNotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial version.
        /// </summary>
        public static string TrialTitle {
            get {
                return ResourceManager.GetString("TrialTitle", resourceCulture);
            }
        }
    }
}
